apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-vite-app
  labels:
    app: node-vite-app
spec:
  replicas: 2 # Runs two copies of your app for high availability
  selector:
    matchLabels:
      app: node-vite-app
  template:
    metadata:
      labels:
        app: node-vite-app
    spec:
      containers:
      - name: app-container
        # Targets your brand-new Artifact Registry path
        image: asia-south1-docker.pkg.dev/practiceproject-495412/new-project-repo/node-vite-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-vite-service
spec:
  type: LoadBalancer # Automatically provisions a public Google IP address
  selector:
    app: node-vite-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

      # prudhvi