# ==========================================
# 1. FRONTEND APP CONFIGURATION
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-vite-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-vite-app
  template:
    metadata:
      labels:
        app: node-vite-app
    spec:
      containers:
      - name: app-container
        image: asia-south1-docker.pkg.dev/practiceproject-495412/new-project-repo/node-vite-app:latest
        ports:
        - containerPort: 5000
---
# ==========================================
# 2. BACKEND API CONFIGURATION
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-backend-app
  template:
    metadata:
      labels:
        app: node-backend-app
    spec:
      containers:
      - name: backend-container
        image: asia-south1-docker.pkg.dev/practiceproject-495412/new-project-repo/node-backend-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "10.80.0.3" # Internal IP address
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_NAME
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: JWT_SECRET
---
# ==========================================
# 3. SERVICE CONFIGURATION
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  type: LoadBalancer
  selector:
    app: node-backend-app # Must match the Deployment label above
  ports:
    - protocol: TCP
      port: 80           # Port exposed to the world
      targetPort: 8080   # Port your backend container is listening on