# ==========================================
# 1. FRONTEND APP CONFIGURATION
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-vite-app
  labels:
    app: node-vite-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-vite-app
  template:
    metadata:
      labels:
        app: node-vite-app
    spec:
      containers:
      - name: app-container
        image: asia-south1-docker.pkg.dev/practiceproject-495412/new-project-repo/node-vite-app:latest
        ports:
        - containerPort: 5000  # UPDATED: Matches your app's actual operational port 5000
---
---
apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  type: LoadBalancer # 🛠️ CHANGED from ClusterIP so your browser can reach it
  selector:
    app: node-backend-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# ==========================================
# # ==========================================
# 2. BACKEND API CONFIGURATION
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend-app
  labels:
    app: node-backend-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: node-backend-app
  template:
    metadata:
      labels:
        app: node-backend-app
    spec:
      containers:
      - name: backend-container
        image: asia-south1-docker.pkg.dev/practiceproject-495412/new-project-repo/node-backend-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "YOUR_PUBLIC_IP_HERE"  # 👈 Put your public IP address here!
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "Prudhviraj@310"
        - name: DB_NAME
          value: "bharath_fresh_db"
        - name: JWT_SECRET
          value: "BHARATH_SECRET_KEY"